name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '20.2-alpine3.17'

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build
      run: |
        cd app
        echo "Current directory: $(pwd)"
        ls -la
        npm run build
        echo "Build complete"
   
    - name: Deploy to server
      run: |
        cd app
        scp -r build/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/bigbee.mnogosushi.kg/
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo systemctl restart nginx'
      env:
        SSHPASS: ${{ secrets.SERVER_PASSWORD }}
