name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Check if dependencies are installed
      run: |
        if [ ! -d "node_modules" ]; then
          npm install
        fi

    - name: Build
      run: npm run build

    - name: Deploy to server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -r build/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/bigbee.mnogosushi.kg/
        echo ${{ secrets.SERVER_PASSWORD }} | sudo -S cp -r /home/binniev/Bigbee-front/app/build/* /var/www/bigbee.mnogosushi.kg/
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'sudo systemctl restart nginx'
      env:
        SSHPASS: ${{ secrets.SERVER_PASSWORD }}
